INSERT INTO book (title, url, identifier, language, word_count, is_original, based_on)
VALUES
  ('20th Century Costume Pattern Design', 'https://ufl.pb.unizin.org/20thcenturypatterndesign/', 1, 'EN', 1806, true, NULL),
  ('12 Key Ideas: An Introduction to Teaching Online', 'https://ecampusontario.pressbooks.pub/onlineteaching/', 2, 'EN', 23332, true, NULL),
  ('21st Century Queer Fashion Brands',   'https://iastate.pressbooks.pub/queerfashionbrands/',   1,   'EN',   210353,   true,   NULL),
  ('2019-2020 Family Medicine Clerkship', 'https://tuftsmedicine.pressbooks.pub/familymedicineclerkship/', 3, 'EN', 266565, true, NULL),
  ('1, 2, 3 Write!', 'https://mhcc.pressbooks.pub/monteverde/', 4, 'EN', 39949, false, 'https://open.lib.umn.edu/writingforsuccess'),
  ('A Guide to Making Open Textbooks with Students', 'https://csupueblo.pressbooks.pub/makingopentextbookswithstudents/', 5, 'EN', 121515, true, NULL),
  ('A parar bien la oreja: cuaderno de comprensión auditiva', 'https://ecampusontario.pressbooks.pub/slch/', 4, 'ES', 12755, true, NULL),
  ('Antología abierta de literatura hispana', 'https://press.rebus.community/aalh/', 6, 'ES', 69619, true, NULL),
  ('Antología abierta de literatura hispana: edición canadiense', 'https://ecampusontario.pressbooks.pub/aalh/', 6, 'ES', 24236, false, 'https://press.rebus.community/aalh/'),
  ('Español para hablantes nativos', 'https://openoregon.pressbooks.pub/spanishbiliteracy/', 4, 'ES', 24405, true, NULL),
  ('La Trousse d’outils d’accessibilité', 'https://ecampusontario.pressbooks.pub/troussedoutildeaccessibilite/', 5, 'FR', 7675, false, 'https://opentextbc.ca/accessibilitytoolkit/'),
  ('Femmes savantes, femmes de science', 'https://scienceetbiencommun.pressbooks.pub/femmessavantes/', 7, 'FR', 33196, true, NULL),
  ('Femmes savantes, femmes de science', 'https://ecampusontario.pressbooks.pub/femmessavantes/', 7, 'FR', 31046, false, 'https://scienceetbiencommun.pressbooks.pub/femmessavantes/'),
  ('قصص من الليالي العربية', 'https://pressbooks.uiowa.edu/makur3/', 6, 'AR', 12791, true, NULL),
  ('A Beginner’s Guide for Transitioning into Colloquial Arabic', 'https://pdx.pressbooks.pub/frommsatoca/', 4, 'AR', 10055, true, NULL),
  ('Tiny Tales from the Sufis', 'https://sufis.pressbooks.com/', 6, 'AR', 25839, true, NULL),
  ('三國演義 (Romance of the Three Kingdoms)', 'https://chinesenotes.com/sanguoyanyi.html', 6, 'ZH', 14715, false, 'https://ctext.org/sanguozhi'),
  ('三國志 (Records of the Three Kingdoms)', 'https://ctext.org/sanguozhi', 6, 'ZH', 84105, true, NULL),
  ('紅樓夢 (Dream of the Red Chamber)', 'https://chinesenotes.com/hongloumeng.html', 6, 'ZH', 44932, true, NULL),
  ('The Dream of the Red Chamber: Book I', 'https://librivox.org/the-dream-of-the-red-chamber-book-i-by-xueqin-cao/', 6, 'EN', 24015, false, 'https://chinesenotes.com/hongloumeng.html'),
  ('An Open Approach to Scholarly Reading and Knowledge Management', 'https://press.rebus.community/scholarlyreading/', 5, 'EN', 2324335, true, NULL),
  ('التدريس عبر الإنترنت', 'https://ecampusontario.pressbooks.pub/aqpr/', 2, 'AR', 39949, false, 'https://ecampusontario.pressbooks.pub/onlineteaching/'),
  ('1, 2, 3 Write!', 'https://oer.pressbooks.pub/writing/', 4, 'EN', 39949, false, 'https://mhcc.pressbooks.pub/monteverde/'),
  ('Una guía para escribir', 'https://oer.pressbooks.pub/escribir/', 4, 'ES', 15949, false, 'https://open.lib.umn.edu/writingforsuccess'),
  ('An Introduction to Medical Documentation for the Physical Therapist Assistant', 'https://psu.pb.unizin.org/ptamedicaldocumentation/', 3, 'EN', 443324, false, 'https://openbooks.lib.msu.edu/isb202/'),
  ('Collegiate Fashion and Activism: Black Women’s Styles on the College Campus', 'https://iastate.pressbooks.pub/collegiatefashionactivism/', 1, 'EN', 6366, true, NULL),
  ('Writing for Success', 'https://open.lib.umn.edu/writingforsuccess/', 2, 'EN', 164035, true, NULL)
